[versions]
picocli = "4.7.6"
snakeyaml = "2.2"
sqlite-jdbc = "3.46.1.3"
jdbi3 = "3.45.4"
jackson = "2.17.2"
jgit = "6.10.0.202406032230-r"
junit = "5.10.3"
assertj = "3.26.3"
wiremock = "3.9.1"
gradle-tooling = "8.10.2"
tomlj = "1.1.1"

[libraries]
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite-jdbc" }
jdbi3 = { module = "org.jdbi:jdbi3-core", version.ref = "jdbi3" }
jackson = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
wiremock = { module = "org.wiremock:wiremock", version.ref = "wiremock" }
gradle-tooling = { module = "org.gradle:gradle-tooling-api", version.ref = "gradle-tooling" }
tomlj = { module = "org.tomlj:tomlj", version.ref = "tomlj" }

[bundles]
test = ["junit-jupiter", "assertj"]
